import type { NextPage } from 'next';
import Image from 'next/image';
import { useSession, signIn, signOut } from 'next-auth/react';
import Head from 'next/head';

const GLogin = (props) => {
  const { data: session } = useSession();
  const login = () => {
    signIn();
    props.setLogin(1);
    localStorage.setItem('token', 1);
  };

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav>
        <div>
          <a href="#">Home</a>
          <a href="#">About</a>
          <a href="#">Contact</a>
        </div>
        <div>
          {session && session.user ? (
            <button onClick={() => signOut()}>Sign out</button>
          ) : (
            <button onClick={() => login()}>Sign in</button>
          )}
        </div>
      </nav>
      <main>
        <div>
          {session && session.user ? (
            <div>
              <div></div>
              <div>
                <h2>Computer Programming Cookbook</h2>
                <p>
                  This is a simple hero unit, a simple jumbotron-style component
                  for calling extra attention to featured content or
                  information.
                </p>
                <p>
                  <a
                    href="https://nextjs.org/docs"
                    target="_blank"
                    rel="noreferrer"
                  >
                    Learn More
                  </a>
                </p>
              </div>
            </div>
          ) : (
            <p>You need to sign in to access the books</p>
          )}
        </div>
      </main>
    </div>
  );
};

export default GLogin;
